### ISSUE TITLE
import cycle ?

### ISSUE THREAD

**Issue by waffleboot** [theartofdevel/golang-clean-architecture#1]
А как так?

internal/domain/author/service.go ссылается на internal/adapters/api/author/interface.go
а
internal/adapters/api/author/interface.go в обратку ссылается на internal/domain/author/model.go
т.е. **import cycle** же

домену нужен интерфейс, который он должен реализовать, а в описании этого интерфейсы идет ссылка на домен и привет, циклическая зависимость

**Comment by o1o1o3** [comment]
я ленивый хорек... 
данная проблема решается созданием DTO для всех переходов данных между слоями

**Comment by Skwol** [comment]
Правильно ли я понимаю, что получается, что book service в адаптерах должен выглядеть примерно так:
```
type Service interface {
	Create(context.Context, *CreateBookDTO) (*BookDTO, error)
	GetByID(context.Context, int64) (*BookDTO, error)
	GetAll(ctx context.Context, limit int, offset int) ([]*BookDTO, error)
}
```
А его реализация в домене соответственно использует эти dtoшки? И соответственно все конвертеры dto->модель и модель->dto лежат в домене?

```
type service struct {
	storage Storage
}

func NewService(storage Storage) book.Service {
	return &service{storage: storage}
}

func (s *service) Create(context.Context, *book.CreateBookDTO) (*book.BookDTO, error) {
	return nil, nil
}

func (s *service) GetByID(context.Context, int64) (*book.BookDTO, error) {
	return nil, nil
}

func (s *service) GetAll(ctx context.Context, limit int, offset int) ([]*book.BookDTO, error) {
	return nil, nil
}
```
